### ISSUE TITLE
Exception ticking world

### ISSUE THREAD

**Issue by OBS3SS1ON** [colochampre/riskofrainmod#3]
net.minecraft.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:899) ~[client-1.20.1-20230612.114412-srg.jar%23598!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:816) ~[client-1.20.1-20230612.114412-srg.jar%23598!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23598!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:663) ~[client-1.20.1-20230612.114412-srg.jar%23598!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23598!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalAccessError: class io.github.colochampre.riskofrain_mobs.entities.StoneGolemEntity tried to access private field net.minecraft.world.entity.Entity.f_19793_ (io.github.colochampre.riskofrain_mobs.entities.StoneGolemEntity is in module riskofrain_mobs@1.1 of loader 'TRANSFORMER' @6da646b8; net.minecraft.world.entity.Entity is in module minecraft@1.20.1 of loader 'TRANSFORMER' @6da646b8)
	at io.github.colochampre.riskofrain_mobs.entities.StoneGolemEntity.<init>(StoneGolemEntity.java:51) ~[riskofrain_mobs-1.20.1-1.1.jar%23551!/:1.1]
	at net.minecraft.world.entity.EntityType.m_20615_(EntityType.java:525) ~[client-1.20.1-20230612.114412-srg.jar%23598!/:?]
	at net.minecraft.world.level.NaturalSpawner.m_46988_(NaturalSpawner.java:231) ~[client-1.20.1-20230612.114412-srg.jar%23598!/:?]
	at net.minecraft.world.level.NaturalSpawner.m_47038_(NaturalSpawner.java:169) ~[client-1.20.1-20230612.114412-srg.jar%23598!/:?]
	at net.minecraft.world.level.NaturalSpawner.m_47045_(NaturalSpawner.java:118) ~[client-1.20.1-20230612.114412-srg.jar%23598!/:?]
	at net.minecraft.world.level.NaturalSpawner.m_47029_(NaturalSpawner.java:108) ~[client-1.20.1-20230612.114412-srg.jar%23598!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:358) ~[client-1.20.1-20230612.114412-srg.jar%23598!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:312) ~[client-1.20.1-20230612.114412-srg.jar%23598!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:305) ~[client-1.20.1-20230612.114412-srg.jar%23598!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:895) ~[client-1.20.1-20230612.114412-srg.jar%23598!/:?]

crash log
https://pastebin.com/FDhGKnwV

**Comment by colochampre** [comment]
Thanks for the report! The **maxUpStep** feature required a little change.
The problem has already been reviewed and there will be an update soon!

**Comment by colochampre** [comment]
Update released! Closing issue
